name: SRPM CI
on:
  push:
    branches:
      - main
    pull_reques:

jobs:
  srpm:
    name: Build SRPM
    runs-on: ubuntu-latest


    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora
      - name: Get source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create container and build srpm
        run: |
          mkdir SRPMS
          podman build -v $PWD:/project --tag rpmbuilder -f Containerfile
          CID="$(podman run --rmi -v $PWD/SRPMS:/root/rpmbuild/SRPMS:rw,z,shared,bind,U -d rpmbuilder)"
          podman exec $CID rpmbuild -bs "SPECS/cie-middleware.spec"
          podman stop $CID
      - name: Version
        run: echo "$(ls SRPMS/*.rpm | cut -d'-' -f3 )"
        id: version
      - name: Release
        run: echo "$(ls SRPMS/*.rpm | cut -d'-' -f4 | cut -d'.' -f1)"
        id: release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SRPMS/*.rpm"
          name: ${{ steps.version.outputs.version }}-${{ steps.release.outputs.release}}
          tag: ${{ steps.version.outputs.version }}-${{ steps.release.outputs.release}}
          commit: main
